### PR TITLE
Feature/list patients

### LINKED ISSUE #23: Once my files are analysed I am able to see a list of my patients each with structured data pulled from their documents
Acceptance criteria:

- [ ] List of sections (one per medical record), each showing fields for:
- [ ] Filename
- [ ] Age
- [ ] Postcode (would this be the patient’s home or hostpital?)
- [ ] Type of cancer
- [ ] Gender
- [ ] Subject to being supplied by Jon’s API:
- [ ] ECOG status
- [ ] Gleason score
- [ ] Disease within prostate 
- [ ] Disease outside prostate 
- [ ] If the data hasn’t been pulled out of the document the field will say ‘Data not found in medical record’
- [ ] A link to view the original medical record PDF
- [ ] Data will need to be shown in fields that can be edited - relates to #24 

This will be working potentially with multiple data objects from the JSON object @cloudstartuptech returns to us from the files being analysed, so it will need to iterate through these. 

Wireframe: 
image

### LINKED ISSUE #24: I am able to edit any of the fields in my list of patients to correct data
Acceptance criteria:

- [ ] Each field outlined issue in #23  will be directly editable so the user can manually change the value

Wireframe:
image

### PR DESCRIPTION
**Pull request by othman-shamla**
resolve #23
resolve #24
### NOTES
* build list patients page with edit functionality
* add  antd library
* the PR does not contain  ( A link to view the original medical record PDF ) functionality

### CODE REVIEW

**Review by MohammedYehia — CHANGES_REQUESTED** [review]
aha

- just a quick note you need to change the color when choosing to edit a field
- and need to add an asterisk in front of age, gender, and cancer type

**Review by wright1 — CHANGES_REQUESTED** [review]
Looks great!!!
small change. spelling - change canser to cancer and maybe provide a unique key to your map functions.

**Comment by martinbagshaw** [comment]
@othman-shamla this appears to be a bit buggy.

When clicking to edit input fields in the top card, an action is initiated in the bottom card. Is this intentional?

Screenshot 2019-10-02 at 21 10 08

**For ui elements:**
- I have a text input already made up [here](https://curenetics-app.netlify.com/enter). Created [here](https://github.com/yalla-coop/curenetics/blob/master/src/components/common/Forms.js) and used [here](https://github.com/yalla-coop/curenetics/blob/master/src/components/pages/enter/index.js)
- I might suggest using [React Select](https://react-select.com/home) which I believe is a bit closer to our figma designs.

**html structure:**
- I see you have a lot of nested sections, many of which are just used for positioning. Sections should be used as content containers, and have a `<h1>` - `<h6>` title in them. If just positioning, you can use `<div>`s - see [MDN on sections](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section)
- use labels rather than spans to label up form elements, see [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) - **for** should be tied to **id**. I actually need to amend one of my PRs to follow this bit of advice!

**css**
- let the columns be full width, at tablet (768px), the layout breaks

Screenshot 2019-10-02 at 21 18 57

- buttons should have an [aria-label](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-label_attribute) and a cursor set to pointer
- Apologies for stealing anyones thunder and doing the initial ui build out first, but it will be a bit easier if we stick to one system: re: theme provider vs my less separated system of common components. We already have a combination of class components and hooks, let's try and lower the cognitive load here - it will help us get things moving a bit quicker, and pick up each other's code with greater ease.

@susanX @wright1 @MohammedYehia  @thejoefriel please discuss. More aligned we can get on the above the better. @othman-shamla thanks for your work!

**Comment by thejoefriel** [comment]
Just a minor thing. Whilst react select is good, I don't think we should use React Select if the team has already agreed to use Antd which has very similar components we can use. Otherwise we're going to end up with a very bloated app with packages.

**Comment by thejoefriel** [comment]
> Apologies for stealing anyones thunder and doing the initial ui build out first, but it will be a bit easier if we stick to one system: re: theme provider vs my less separated system of common components. We already have a combination of class components and hooks, let's try and lower the cognitive load here - it will help us get things moving a bit quicker, and pick up each other's code with greater ease.

On this point @mr-bagglesworth , I think perhaps there's been an issue that there was no documentation created on what had been created and what can be used. This makes it hard for people to know what you have created to be used and what still needs to be created.  Maybe you could put together a very quick run through for people via an issue that you can then share on slack?

**Comment by martinbagshaw** [comment]
@joe I was hoping the general naming conventions I was giving to files and components would have made this obvious enough. Will do a run through either tonight or tomorrow

**Comment by othman-shamla** [comment]
@mr-bagglesworth 
### edit input fields bug :-
this just because the Filename is accidentally duplicated in the dummy data
### For ui elements :-
* the input its not generic and i can't use it, see the picture below
screen-input
* i was using  React Select  before we agreed on the ant design

### html structure and css :-
* yeb i refactor the code as the suggestion really thanks
* i'm trying to make the layout looks good across any width for now its break at 1024 hhhh

**Review by wright1 — CHANGES_REQUESTED** [review]
###  **In full-width there seems to be an extra column**
### **Also there needs to be a gap between columns**
patientList

**Comment by susanX** [comment]
This looks really good!

- add box-shadow to white cards. 

Layout
Make gap between each key, value and 'edit' smaller than the gap between columns.

Type of cancer [not cancers]
Age [capital A]
Gender [capital G]
Postcode [capital P]

**Review by wright1 — DISMISSED** [review]
mobileView
**Mobile View also seems like it is off center**
**Sorry Othman I am incorrect  it looks fine in mobile View**
correct

**Comment by martinbagshaw** [comment]
@othman-shamla happy to jump in on this and tidy it up if you want - probably on saturday now as I'm tired, thanks for your work.

**Review by martinbagshaw — APPROVED** [review]
I've refactored a bit to split up the index.js file into separate components, and align styles more with the rest of the app. There are a few more things to do with regards to styling, but they shouldn't block, and we can do them at a later date.

Would like to draw attention to:
1 - README.md in components folder - this serves as documentation
2 - antd is a pain to style. The dropdown displays outside of react, which is probably going to make it impossible to style. Even trying to style in the reset file did not work. Debugging screenshots + how to debug this dropdown below:

Screenshot 2019-10-07 at 01 33 53

^ add this in your console, then click the dropdown. The console will pause in debugger and you can use dev tools as normal.

Screenshot 2019-10-07 at 01 31 28

^ shows the dropdown outside of react.

**Comment by martinbagshaw** [comment]
Hi all (@MohammedYehia @othman-shamla @susanX @wright1 ), please get this merged in, along with Susan's work.

This should be pretty much aligned with our designs, and mobile responsive now.

Got the dropdowns styled, added component implementation notes, etc.

Moving forward, I would encourage you to have a close look at [patient-list](http://localhost:3000/patient-list) <- (a link to open it when running the app locally). What is in here is reasonably complex, though I have split it out a bit. I think we should use a similar, if not exactly the same data structure here as we do in [enter patient data](http://localhost:3000/enter), as they are both concerned with adding and editing patient details.

**Comment by martinbagshaw** [comment]
> aha
> 
> * just a quick note you need to change the color when choosing to edit a field
> * and need to add an asterisk in front of age, gender, and cancer type

@MohammedYehia I have addressed this now.

**Review by MohammedYehia — APPROVED** [review]
@mr-bagglesworth really appreciate the work you have done on this PR
and the documentation you put.
just a note on this pic one the alignment 


if this is fine then you should merge

**Pull request merged**
