### PR TITLE
Feature/modal

### PR DESCRIPTION
**Pull request by wright1**
This is a pop up modual which warns user about information usage. It relates to:
**Add warning message on the landing page #90** 
screen 2 on the figma prototype.

### CODE REVIEW

**Comment by othman-shamla** [comment]
i think using modal from ant design will be better than creating you own
because its like have conflict with the header component
i can help here if your busy with something i will refactor the branch and using the modal and approve it
@wright1 

Screenshot from 2019-10-16 12-19-37

**Comment by wright1** [comment]
In the figma it shows the modal overlapping the header.
I didn't think it was an issue. I thought it was a way to make to modal stand out. 
Are you suggesting we use ant design instead?

**Comment by othman-shamla** [comment]
i'm taking about the black background not the body of the modal

**Comment by wright1** [comment]
You don't want the black background?

**Comment by othman-shamla** [comment]
no its just the background need some adjustment to cover all the screen

**Comment by susanX** [comment]
Works well! And looks good. Just a few small points.

Make button oranage before it 's clicked. Capital C for Consent.
Add more space top and bottom svg.
Make Title smaller (on Figma it is just 2px bigger than text) black , add space under the title.
Add a bit more padding between the text and button and the box border.
The inactive page on Figma has white 50% added to it to give the paler look.

#51
Edits to clear warning box-->

Medical information extracted is immediately pseudo-anonymised and then encrypted before analyses
[note: change: 4th word should be is not are]

Medical professionals must only used this app on a secure or trust-approved computer. The uploaded files(s) will be stored locally but wiped when you close the app.

This current software iteration is only optimised for scientific and research purposes. It must not serve as aid in clinical decision making.

**Review by susanX — APPROVED** [review]

**Review by susanX — APPROVED** [review]

**Pull request merged**
