### PR TITLE
Feature/patient original file

### PR DESCRIPTION
**Pull request by othman-shamla**
related #60 #80
### NOTE
  * in upload page i left the state of the input to app to pass it to patient-list page
  * i used modal component from ant-design to view the pdf
  * i used [react-pdf](https://www.npmjs.com/package/react-pdf) to render the pdf from state

### problems
 * viewing the pdf its not that good in mobile
 * there is a warning from react-pdf, can't make it disappear

### how it works?
 * go to /upload page 
 * upload pdf that match any fileReference name in dummy data like (001001.pdf , 001131.pdf)
 * pressing upload button will send you the patient-list page (for now)
 * press (Click to view original file) button that match the pdf name you uploaded

### CODE REVIEW

**Comment by wright1** [comment]
@othman-shamla I'm finding it challenging to follow your code. This is not a reflection of your code more a lack of my knowledge. Would it be possible for you to put a few comments in especially around your mapping/filter functions? Thank you.

**Comment by wright1** [comment]
@othman-shamla Thanks for the comments they were really helpful.
The only question I have is why do we have to change the name of the file before we're able to view it?

**Comment by othman-shamla** [comment]
this PR just to demonstrate the functionality of viewing the PDF of your uploaded file this restriction will removed in this issue #21 after making sure the API is running

so this restriction is just because in the dummy data we have patients fileReference with 001001, 001131
my assumption for now fileReference is just the name of the PDF

in other words its just for linking the patient dummy data to the PDF that we uploaded to demonstrate the functionality
@wright1

**Review by wright1 — COMMENTED** [review]
Thanks for the comments. 
This wasn't an easy bit of code!!!!! 
The only thing is I get this error on your branch when compiling
**Critical dependency: require function is used in a way in which dependencies cannot bestatically extracted**
this may be spefic to me, if so I will approve and merge because it still renders and looks great on the screen

**Comment by othman-shamla** [comment]
yes this the warning i told you about on the stand-up yesterday 
its working yes, but i cant remove this warning.

**Comment by wright1** [comment]
yes, this is a know issue with react/pdf
The solution is here:
https://github.com/wojtekmaj/react-pdf/issues/280
scroll down to @maciejmatu I found that his solution work but it means taking a few steps.
including adding another dependency, creating another file with a small script , also changing the json so that it include a new start script.
It was shortly after this I decided to use another module.
How important is it that this error is resolved?

**Comment by othman-shamla** [comment]
this a workaround for not showing the warring, not a solution
but i'm happy to apply it

**Comment by othman-shamla** [comment]
i don't know if its okay to add two modules (craco, lodash), i don't think its worth it
i think the solution, just to make sure CI for them pass
but for us travis and netlify, there are green and no problem when building the app
what do you think @wright1 ?

**Comment by wright1** [comment]
I think you may be right @othman-shamla 
What do you think @thejoefriel ???

**Review by wright1 — APPROVED** [review]

**Review by MohammedYehia — APPROVED** [review]

**Pull request merged**
