### PR TITLE
add select files button

### PR DESCRIPTION
**Pull request by wright1**

### CODE REVIEW

**Comment by martinbagshaw** [comment]
@wright1 it may be worth asking for Joe's advice on this. Do we really have to use a ref to get pdf file details from an upload?

**Comment by wright1** [comment]
@mr-bagglesworth sure we can ask Joe, but I believe an file input is the only way to open the file manager. The browser cannot open the file manager. But if there is another way I'm good to go!!!

**Comment by martinbagshaw** [comment]
@wright1 fair enough. If it works, merge it in!

**Comment by martinbagshaw** [comment]
@wright1 feel free to push your latest version. Happy to help regarding your z-index / overlap issue when I get a chance.

**Comment by martinbagshaw** [comment]
@wright1 can this branch now be discarded?

**Comment by MohammedYehia** [comment]
@wright1 should this be closed?

**Pull request closed without merging**
