### PR TITLE
Style setup with colours from figma

### PR DESCRIPTION
**Pull request by martinbagshaw**
- Relates to [this pr](https://github.com/yalla-coop/curenetics/pull/46), making sure commit is under my personal account, not work
- #42 and #9 , and also [Figma](https://www.figma.com/file/BaIHfKxJN8zhXlVoTxlTJu7B/CURENETICS2?node-id=47%3A261)

### CODE REVIEW

**Comment by wright1** [comment]
Hi Martin, 
Is this to be used with styled-components theme provider or is this to be used separately?

**Review by wright1 — CHANGES_REQUESTED** [review]
Martin, 
I wanted to know if this was to be used with the ThemeProvider that styled components use.

**Comment by susanX** [comment]
See Figma fonts Lato and Roboto are being used. The logo is not Domus or Sofia. I will grab it from the Branding doc.

**Comment by wright1** [comment]
I would say Domus is a closer match to what is in the branding pdf, I don't know about Sofia.

**Comment by martinbagshaw** [comment]
Charmaine - we could use it with a theme provider, I tend to use this sort of thing in template literals though - ${colours.red} for example. So whatever people prefer.

Susan I will update this pr accordingly this evening.

**Comment by martinbagshaw** [comment]
@susanX I have made updates to this pr, but can't seem to push to this branch again - says the remote contains work I do not have locally. Pulling / fetching does not seem to help either unfortunately.

Edit: was probably because I had a file open in my IDE that had been deleted by git. Probably...

**Pull request closed without merging**
