### PR TITLE
Feature/select to upload

### PR DESCRIPTION
**Pull request by wright1**
Please test trying to upload non-pdf's and test selecting multiple pdf's. Also I forgot to set the z-index on the header, I plan to replace the button with Martin's once his has been merged. At the moment the when scrolling the button overlaps the header.
Thank you.

### CODE REVIEW

**Comment by wright1** [comment]
I just remembered I changed eslint so that it no longer wants props proptoType I'm not sure if everyone is OK with that. If not remove!

**Review by martinbagshaw — APPROVED** [review]
@wright1 good work. Feel free to amend with my + button when the pr is merged in. I could not replicate the overlap with the header / navbar, but perhaps that may be due to its fixed positioning, and the z-index being set on this button, and not the header / navbar.

I noticed @susanX set it to absolute in her pr. Perhaps we should, as a team, decide if we want it to be sticky (fixed to top of the screen), or absolute (not sticky).
@MohammedYehia @othman-shamla do you have any thoughts on this?

One more note: would be good to add cursor: pointer, and `aria-label` to the button: https://developers.google.com/web/tools/lighthouse/audits/button-name

For now, happy to merge this in

**Comment by MohammedYehia** [comment]
@mr-bagglesworth 
if it's fixed then it would be good for faster navigation between the pages but with absolute, it could give us more space on mobiles I am not sure 🤷‍♂️ but if you are talking about the position to be `position: sticky` then we shouldn't use it because of the old browser compatibility

**Comment by martinbagshaw** [comment]
> @mr-bagglesworth
> if it's fixed then it would be good for faster navigation between the pages but with absolute, it could give us more space on mobiles I am not sure 🤷‍♂️ but if you are talking about the position to be `position: sticky` then we shouldn't use it because of the old browser compatibility

@MohammedYehia I don't think you understand. There are no browser compatibility issues at all here. It might help to examine the code a little more closely.

with either [fixed](https://developer.mozilla.org/en-US/docs/Web/CSS/position#Fixed_positioning) or [absolute](https://developer.mozilla.org/en-US/docs/Web/CSS/position#Absolute_positioning) positioning, I am offsetting `Main` by the height of the navbar, so that we get no overlap.

**Comment by MohammedYehia** [comment]
@mr-bagglesworth I think the first part was the answer to your question
`if it's fixed then it would be good for faster navigation between the pages but with absolute, it could give us more space on mobiles I am not sure`
finally, I mentioned the position sticky just in case you were referring to it

**Comment by susanX** [comment]
..sticky (fixed to top of the screen), or absolute (not sticky).
I would go with not sticky 
1. it takes up too much room on a mobile
2. it is better to see new information, you get tired of seeing the header all the time.

**Comment by susanX** [comment]
add image alt.
Still reviewing:

**Comment by susanX** [comment]
Looks great!
It works well, it adds pdfs
and removes listed pds

Small points
Use an svg for the circle and plus icon.
What to do :  (no space before : )
PDFs only (no &apos;) also text-align: left
When you’ re (no space before re)
Use bold text as Figma

**Comment by wright1** [comment]
@susanX what is the reason for using svg? I am using the image you created for me?

**Comment by wright1** [comment]
@susanX Where do you want the bold text? The circle and plus icon are temporary.

**Comment by susanX** [comment]
What to do:
1. Click on the **Add your files** button to select patients file(s). Only PDF files can be selected.
2. Delete any file at any time
3. When you’re ready click the **Upload** button to upload files.

The svg can wait merg after the text correction are done.

**Pull request merged**
