### PR TITLE
configure eslint

### PR DESCRIPTION
**Pull request by MohammedYehia**
- fix indentation by tabs instead of spaces
- ignore the warning for `jsx` extension

I am facing some problem with Eslint and I guess @othman-shamla also facing some problem 
I would like to try and do some configuration on Eslint if it's fine with all of you

### CODE REVIEW

**Review by susanX — COMMENTED** [review]
OK - configure linter for tabs instead of spaces & add iqnore for js/jsx xtension

**Review by martinbagshaw — CHANGES_REQUESTED** [review]
Looks good @othman-shamla . I'm sure there is a way to have icons as .js, will find it out at some point, but got bigger fish to fry right now I think.

One thing that is driving me crazy is passing props into styled components. I will attach a screenshot to demo. If you can work that out, that'll be great.

I think `no-confusing-arrow` is the thing to disable.

Screenshot 2019-10-02 at 01 17 26

**Comment by wright1** [comment]
@mr-bagglesworth What is the error message you get?  It is easier to find out how to disable it if we have the error message.

**Review by wright1 — COMMENTED** [review]
This seems fine to me. I have replied to @mr-bagglesworth comment regarding his requested change.

**Comment by martinbagshaw** [comment]
> @mr-bagglesworth What is the error message you get? It is easier to find out how to disable it if we have the error message.

^ `no-confusing-arrow` https://eslint.org/docs/2.0.0/rules/no-confusing-arrow

**Comment by martinbagshaw** [comment]
@MohammedYehia pulling down and running this branch seems to fix the complaint passing in props to styled components. However, even after selecting format on save in vs code, the linter fails to format the App file with the new indentation rules.

There must be a conflicting rule somewhere.

Screenshot 2019-10-02 at 21 00 49

**Comment by MohammedYehia** [comment]
I will try to edit the eslint config or maybe pull it from one of our other working project to fit with eslint and prettier

**Comment by MohammedYehia** [comment]
@wright1 @mr-bagglesworth @susanX @othman-shamla 
I've added the changes give it a try and merge if is everything fine

**Pull request merged**
